### ISSUE TITLE
Paul Gilligan

### ISSUE THREAD

**Issue by pauldavidgilligan-msm** [oscar-stack/vagrant-auto_network#27]
Great work, would you be able to make a slight improvement ? I have a set of docker hosts run via vagrant for business services however one of the hosts will be internal DNS and I would like to be able to reserve an IP from the pool for this host. It is a bit tricky with vagrant / docker to pickup the docker IP reliably so using this feature and your plugin would be a winner.

Paul

**Comment by Sharpie** [comment]
The strength of auto_network is to dynamically assign IP addresses to VirtualBox hosts. If you need a static IP address, then the best bet is to use Vagrant's static IP support directly:

https://www.vagrantup.com/docs/networking/private_network.html#static-ip
