### ISSUE TITLE
How to configure AutoNetwork.default_pool

### ISSUE THREAD

**Issue by timidri** [oscar-stack/vagrant-auto_network#30]
I am using oscar to build puppet masters and agents. I need to change the network configuration

The docs here: https://github.com/adrienthebo/vagrant-auto_network say that I can configure AutoNetwork.default_pool to something custom. Where can I do that? If I add that at the top of the Vagrantfile, it doesn’t seem to work. 

Thanks in advance!

**Comment by singularo** [comment]
I have the same problem, this functionality seems broken, and the default range overlaps with network resources I need to access.

Any pointers from anyone on getting it working much appreciated.

**Comment by singularo** [comment]
And of course, now I figured it out.

It looks like if you already have a pool, you need to delete that first with something like:
`rm ~/.vagrant.d/auto_network/pool.yaml`

Then when the next machine is launched, it uses the AutoNetwork.default_pool parameter correctly, and future `vagrant up` just get entries out of that pool automatically.

**Comment by cdracars** [comment]
wow... this should be added to the readme.

**Comment by generalredneck** [comment]
Just adding some to this... if you are looking to change to a different default... it's possible by both swapping out the new default range in ~/.vagrant.d/auto_network/pool.yaml with the old one... and then adding all of the IPS on that range to the pool attribute.

I personally found a VPN hardwired to restrict certain IP ranges so I went and did a search and replace to swap all of mine. Keep in mind you have to do this to your hosts file too if you are using vagrant-hostsupdater in conjunction with this one.
